name: "movie_success"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  movie_success:
    +materialized: view
